CREATE DATABASE Diplomados;


USE Diplomados;


CREATE TABLE Sede(
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Localidad VARCHAR(50) NOT NULL
)


CREATE TABLE Profesor(
	TypeID VARCHAR(10),
	ID VARCHAR(15),
	Nombre VARCHAR(20) NOT NULL,
	Apellido VARCHAR(20) NOT NULL,
	Email VARCHAR(40),
	PRIMARY KEY(TypeID, ID)
)


CREATE TABLE Curso(
	ID VARCHAR(10) PRIMARY KEY,
	Nombre VARCHAR(20) NOT NULL,
	FechaInicio DATE NOT NULL,
	FechaFinal DATE,
	Estado VARCHAR(10) NOT NULL
)


CREATE TABLE Estudiante(
	TypeID VARCHAR(10),
	ID VARCHAR(15),
	Nombre VARCHAR(20) NOT NULL,
	Apellido VARCHAR(20) NOT NULL,
	Email VARCHAR(40),
	PRIMARY KEY(TypeID, ID)
)


CREATE TABLE Biblioteca(
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Nombre VARCHAR(20) NOT NULL
)


CREATE TABLE Libro(
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Tipo VARCHAR(7) NOT NULL,
	Titulo VARCHAR(40) NOT NULL,
	Autor VARCHAR(20) NOT NULL,
	NoEjemplares INT,
	FechaPublicación DATE,
	Genero VARCHAR(20) NOT NULL,
	NoPaginas INT
)


CREATE TABLE RevistaCientifica(
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Tipo VARCHAR(7) NOT NULL,
	Titulo VARCHAR(40) NOT NULL,
	Autor VARCHAR(20) NOT NULL,
	NoEjemplares INT,
	FechaPublicación DATE,
	Tematica VARCHAR(20) NOT NULL,
	Periocidad INT
)


CREATE TABLE InformesInvestigacion(
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Tipo VARCHAR(7) NOT NULL,
	Titulo VARCHAR(40) NOT NULL,
	Autor VARCHAR(20) NOT NULL,
	NoEjemplares INT,
	FechaPublicación DATE,
	Tematica VARCHAR(20) NOT NULL,
)