--Modificar tablas

USE Diplomados;

ALTER TABLE Libro
ALTER COLUMN Tipo VARCHAR(15) NOT NULL;

ALTER TABLE RevistaCientifica
ALTER COLUMN Tipo VARCHAR(15) NOT NULL;

ALTER TABLE RevistaCientifica
ALTER COLUMN Periocidad VARCHAR(15);

ALTER TABLE InformeInvestigacion
ALTER COLUMN Tipo VARCHAR(15) NOT NULL;

ALTER TABLE InformeInvestigacion
ALTER COLUMN Autor VARCHAR(40) NOT NULL;

ALTER TABLE InformeInvestigacion
ALTER COLUMN Tematica VARCHAR(40);

--Condicion Extra para los NEWIDS();
ALTER TABLE Sede
ADD Nombre_Sede VARCHAR(12);

ALTER TABLE Libro
ALTER COLUMN Autor VARCHAR(MAX) NOT NULL;

--Arreglar errores en isertarDatos
ALTER TABLE Libro
ALTER COLUMN Genero VARCHAR(MAX) NOT NULL;

ALTER TABLE RevistaCientifica
ALTER COLUMN Tematica VARCHAR(MAX) NOT NULL;

ALTER TABLE RevistaCientifica
ALTER COLUMN Titulo VARCHAR(MAX) NOT NULL;

ALTER TABLE InformeInvestigacion
ALTER COLUMN Titulo VARCHAR(MAX) NOT NULL;